name: upload

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DIRECTCLOUDBOX_SERVICE: ${{ secrets.DIRECTCLOUDBOX_SERVICE }}
      DIRECTCLOUDBOX_SERVICE_KEY: ${{ secrets.DIRECTCLOUDBOX_SERVICE_KEY }}
      DIRECTCLOUDBOX_CODE: ${{ secrets.DIRECTCLOUDBOX_CODE }}
      DIRECTCLOUDBOX_ID: ${{ secrets.DIRECTCLOUDBOX_ID }}
      DIRECTCLOUDBOX_PASSWORD: ${{ secrets.DIRECTCLOUDBOX_PASSWORD }}
      DIRECTCLOUDBOX_NODE: '1' # "1" means "My Box" folder
      DIRECTCLOUDBOX_FILE_PATH: 'README.md' # set a file or directory
    steps:
      - uses: actions/checkout@v2
      - uses: tk3fftk/upload-DirectCloud-BOX-action@v1.0
